openapi: 3.0.3
info:
  title: Onboarding API
  description: STD22027
  version: 1.1
servers:
  - url: https://STD22027.com
tags:
  - name: Students
    description: Everything's about students
paths:
  /students:
    post:
      tags:
        - Students
      summary: Create a student in the store
      description: creat a student
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            example: 1
            required: true
        - name: name
          in: path
          schema:
            type: string
            example: Rakoto
            required: true
        - name: birthDate
          in: path
          schema:
            type: string
            example: 2000-01-01
            required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                example: [1, Rakoto, 2000-01-01]

        500:
          description: Internal server error
    get:
      tags:
        - Students
      operationId: get student by Id
      summary: Find student by Id
      description: Find a student
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                items: 
                  - $ref: 

        500:
          description: Internal server error
    delete:
      tags:
        - Students
      operationId: deleteStudents
      summary: Deletes a student
      description: delete a student
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            required: true
      responses:
        200:
          description: Resource deleted
          content:
            application/json:
              schema:
                type: integer
                example: 1
        500:
          description: Internal server error
    put:
      tags:
        - Students
      operationId: updateStudent or createNewStudent
      summary: update student or create new student
      description: update a student
      parameters:
        - name: name
          in: path
      requestBody:
        description: student to be created
        content:
          application/json:
            schema:
              items: 
                $ref: 
        required: true
      responses:
        200:
          description: created or update student
          content:
            application/json:
              schema:
                type: string
                example: Rasoa
        500:
          description: Internal server error
