openapi: 3.0.3
info:
  title: Onboarding API
  description: STD22027
  version: 1.1
servers:
  - url: https://STD22027.com
tags:
  - name: Students
    description: Everything's about students
paths:
  /students:
    post:
      tags:
        - Students
      summary: Create a student in the store
      description: Create a student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                name:
                  type: string
                  example: Rakoto
                birthDate:
                  type: string
                  example: 2000-01-01
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                example: [1, Rakoto, 2000-01-01]
        '500':
          description: Internal server error

    get:
      tags:
        - Students
      operationId: getStudentById
      summary: Find student by Id
      description: Find a student
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '500':
          description: Internal server error

    delete:
      tags:
        - Students
      operationId: deleteStudent
      summary: Deletes a student
      description: Delete a student
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            required: true
      responses:
        '200':
          description: Resource deleted
          content:
            application/json:
              schema:
                type: integer
                example: 1
        '500':
          description: Internal server error

    put:
      tags:
        - Students
      operationId: updateOrCreateStudent
      summary: Update student or create new student
      description: Update a student
      parameters:
        - name: name
          in: path
      requestBody:
        description: Student to be created or updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Created or updated student
          content:
            application/json:
              schema:
                type: string
                example: Rasoa
        '500':
          description: Internal server error

components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Rakoto
        birthDate:
          type: string
          example: 2000-01-01
  
